dnaString = 'TCAGGAAATCCTAGTTGCACCTAACTCCTCCGCGCTTTACGATGAGTGCCAAGTACGCTGACCATGAGGACTTGAGTATGAGGGCCCCCCGTCCTCACGGCTGTAGACGGATGTGTGATCAGAGAACTGTAACTTATCAATAGCGCCCCGTCTGTACTTTGGTCCGCGAACTCGAAGCGATGTCGAAAACGTAAAGTGGGGTTACTTGTGCGGAACTTAACAGCATGAAAATCGCTTAGATAGACGGGAAATGTCCTAGGTTAAGGTGGGGCCGCACTTTAATCGGCCCAAGCCATTAGTAATGTTGTACCTTCCGTCCCCGCACCAGGGATGAGAACCTATACAACGTGGATCATTCACACGCTTGCCTTGTGGCGACGTCTGGGAAAGCCACATAGGGCCTGGATTGATCCGCAGCCCAGACAGCCAGTCTGGTACTAACACGGTTACAGCCGTGCGCATTCCGACTAGCTTGGCCCCTTGATCAGTTGTTCCGGAGTTTAGCCCCGATATTACCATACTTCCTTACTAGATGCTGAGTGGTATAGTGTTTTTGGGTGTTAGTATCGTATACAAGCAGCGCTGCTTAATTACACCCCTTTGAAGAGCCGCCTATGGGGTCTGAAGCTATCAGGCTAGTACGCGAGTGCATGGGTTTGTGGGGTTTAGTATCACAGGCCCGCGGACGCTACGGGCGACATAGAAGTGGAACATTCATCTTTATGTGCATAAGACAGCGTTTGTCCACTTCTAACGTAAGCCCCCTATAAGTACGTGCGGACCTGCATCGAGTCCGAGGAATTTTAGGTCAGTTTTTACCTCGCGAGCAGGCATACAAATAGGATTTTCTGGATCTCA'


def DNACounter(DNA):
    aCount = 0
    gCount = 0
    cCount = 0
    tCount = 0
    
    for i in DNA:
        if i is 'A':
            aCount += 1
        elif i is 'G':
            gCount += 1
        elif i is 'C':
            cCount += 1
        else:
            tCount += 1

    print (str(aCount) + ' ' + str(cCount) + ' ' +
           str(gCount) + ' ' + str(tCount))


DNACounter(dnaString)
        
    
