dna = 'TGTCTATGGCGAGTCTAGATAGTTCTGTCACCTGACGTCAGGTGTGAATTAAGGCTCAATCCAACTGGATCGGGCCGCGCAGTTTATCGTAGGGGCTGTCACGACAAGCCGCGCGCTCCCGCAAGTATAGGGGTTGTAAACTCTGATGCTCCGAGAGGGGTGTATACATAAACACAAGACACAAGCTCGAGTATTTTTGTGTGCCAGTGAAAGAGGATCCTAGAATATGCAGTCACGGGGACTTGGGGACAGACCGGCTCAATCGAGTTCTATGCACTGGTAAAGCTCTTATTCCACTGGCTCACCTATGGTCGATGTACCGTTCGCAGTCTAATGGAATTGCCTGATCTCACGCAACTTAGTCCTTGCTTGATCTGCAACCCCTGACAGTCTTTAAAGTGGTAATGAACGGACCAGCTTACTAGTGAAGGAAAGTAGCAGGGGCGTGAGGACGCTCGGCCCACGCAATTAGACTTCAGACGACCGAACCAGGGGAGCATTGGCTAGGGCAGAGGTCATAACGCGATAGAACTCTAGAGAGAGAATCCCCTGAAACGCCTAACAATAAGCCCATGTGACTCTGTTCGGTATTCGGAAATTGACTTGCTAACAGACTTTTACATGCGTCGAGCTCTGGGGATACATCCGCATTTAGTTGGATTAACCAGGGCAAACCATTAATTGCAGGAGCAGAGACAGCGGTCATCATCTTTCCTAACCAAATGGCTACAAATATCATCACACGCCCGAATGTACAGCAAAACTCCCACTCTAGCTCGATGGTTCGCTCCGCCCACTCCGCTAGCTAAAACTTCAGAG'

def reverseComp(string):
    comp = ''
    
    for i in range(1, len(string) + 1):
        comp = comp + string[-i]

    secondComp = ''

    for i in range(len(string)):
        if comp[i] is 'A':
            secondComp = secondComp + 'T'
        elif comp[i] is 'T':
            secondComp = secondComp + 'A'
        elif comp[i] is 'G':
            secondComp = secondComp + 'C'
        else:
            secondComp = secondComp + 'G'

    print(secondComp)
    

reverseComp(dna)
